### ISSUE TITLE
cannot import name 'RewardModel'

### ISSUE THREAD

**Issue by WoojuLee24** [montrealrobotics/dal#1]
I installed tensorflow, pytorch, tensorboardX, openai gym, openai baseline, tkinter, and dal
But when I executed the program by 'python main.py' , 
![image](https://user-images.githubusercontent.com/39393017/56404674-f9ff6880-62a2-11e9-8a10-21485f5e1658.png)
ImportError: cannot import name 'RewardModel'
I can't find any module named RewardModel.
Should I make the RewardModel on my own? If it does, could you explain how to make it?

Plus,  I got another error when I executed the program, 
ModuleNotFoundError: No module named 'config'
ModuleNotFoundError: No module named 'utils.py'
error was found.
I copied dal/sim/config.py to dal folder and copied dal/utils.py to dal/a2c_ppo_acktr folder.
Is it right?

Thanks so much

**Comment by saikrishna-1996** [comment]
Hey, sorry for the late reply and thanks for your patience! 
- It's the same utils folder which was there in /dal/ I have now added it to /dal/a2c_ppo_acktr 
- I have now added the config.py and RewardModel
More information about Reward Model: It wasn't used in the final results reported in the paper. So I didn't add it earlier in the networks.py. But, it's a nice tool to experiment with! This would be particularly useful if our reward function is sparse, see: https://arxiv.org/abs/1804.06459
